### ISSUE TITLE
Expanding the support for Nanopore sequencing data

### ISSUE THREAD

**Issue by llk578496** [CDCgov/mycosnp-nf#116]
**Is your feature request related to a problem? Please describe.**

The current mycosnp-nf pipeline only supports Illumina sequencing data, which limits its applicability in clinical microbiology laboratories that are increasingly utilizing Nanopore sequencing technology, particularly when investigating Candida auris outbreaks. The development of this pipeline has been greatly appreciated, as it helps to standardize the WGS analysis, especially for Candida auris.

**Describe the solution you'd like**

Expand the mycosnp-nf pipeline to provide support for Nanopore sequencing data analysis, in addition to the existing Illumina support. This would allow clinical microbiology laboratories to leverage the `mycosnp-nf` pipeline for comprehensive genomic analysis of Candida auris isolates, regardless of the sequencing platform used, ensuring wider applicability and utility of the tool in outbreak investigations and epidemiological studies.

**Describe alternatives you've considered**
-

**Additional context**
-

Thank you very much!

Best regards,
Eddie

**Comment by zmudge3** [comment]
Hi Eddie,

Thanks for your request, and I apologize for the delayed response.

We agree that support for long read sequencing should be added. We're currently in the process of evaluating tools that are specific to nanopore reads (e.g. for read cleaning and alignment steps). I'm going to close this issue here, but we are actively working on this.
